language: node_js
before_install: dpkg --compare-versions `npm -v` ge 5.8 || npm i -g npm@latest
install:
  - npm ci
cache:
  directories:
    - "$HOME/.npm"
node_js:
  - "node"
  - "8"
  - "6"
script: npm run test-with-coveralls
services:
  - mongodb
before_script: sleep 15
